---
- name: user_deletion playbook
  hosts: all
  become: true
  vars_files:
    - user.yaml
  tasks:
  - name: deleting a user
    user:
      name: "{{ user }}"
      state: absent
      remove: yes
