---
- name: installing packages and starting services
  hosts: all
  become: true
  tasks:
    - name: installing packages
      yum:
        name: httpd
        state: installed
      when: ansible_os_family == "RedHat"
   
    - name: starting httpd/apache
      service:
        name: httpd
        state: started
      when: ansible_os_family == "RedHat"

    - name: installing packages
      apt: 
        name: apache2
        state: present
      when: ansible_os_family == "Debian"

    - name: starting httpd
      service:
        name: apache2
        state: started
      when: ansible_os_family == "Debian"
    
    - name: copying a html file
      copy:
        src: /opt/ansible/index.html
        dest: /var/www/html
        mode: 0777
