---
- name: installing tomcat
  hosts: all
  become: true
  tasks:
  - name: tomcat installation
    yum:
      name: java
      state: installed
 
  - name: download tomcat packages
    get_url:
      url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.74/bin/apache-tomcat-9.0.74.tar.gz
      dest: /opt/
  
  - name: unzip the files
    unarchive: 
      src: /opt/apache-tomcat-9.0.74.tar.gz
      dest: /opt
      remote_src: yes

  - name: adding permissio to the startup.sh file 
    file:
      path: /opt/apache-tomcat-9.0.74/bin/startup.sh
      mode: 0777

  - name: running the command
    shell: nohup ./startup.sh
    args:
      chdir: /opt/apache-tomcat-9.0.74/bin
