---
- name: playbook for uninstalling apache
  hosts: all
  become: true
  tasks:
    - name: stop httpd service
      service:
        name: httpd
        state: stopped
    - name: remove httpd
      yum:
        name: httpd
        state: absent
